export const COUNTRIES = [
  "United States",
  "United Kingdom",
  "Canada",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Netherlands",
  "Belgium",
  "Switzerland",
  "Austria",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Poland",
  "Portugal",
  "Greece",
  "Ireland",
  "Czech Republic",
  "Romania",
  "Hungary",
  "Australia",
  "New Zealand",
  "Japan",
  "China",
  "India",
  "South Korea",
  "Singapore",
  "Malaysia",
  "Thailand",
  "Indonesia",
  "Philippines",
  "Vietnam",
  "Hong Kong",
  "Taiwan",
  "Brazil",
  "Mexico",
  "Argentina",
  "Chile",
  "Colombia",
  "Peru",
  "Venezuela",
  "South Africa",
  "Egypt",
  "Nigeria",
  "Kenya",
  "Israel",
  "Turkey",
  "Saudi Arabia",
  "United Arab Emirates",
  "Qatar",
  "Kuwait",
  "Russia",
  "Ukraine",
  "Other",
];

export const COUNTRY_DISPLAY_NAMES: Record<string, string> = {
  "United States": "America",
  "United Kingdom": "UK",
};
